name: "Setup"
description: "Setup"
runs:
  using: "composite"
  steps:
    - run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
      shell: bash
      if: runner.os == 'Linux'
    - run: echo "ANCHOR_VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
      shell: bash
    - run: git submodule update --init --recursive --depth 1
      shell: bash
