//! Build-time support for linking hand-written SBPF assembly into Anchor v2
//! programs via `global_asm!`.
//!
//! # Usage
//!
//! ```toml
//! # Cargo.toml
//! [dependencies]
//! anchor-asm = { path = "..." }
//!
//! [build-dependencies]
//! anchor-asm = { path = "..." }
//! ```
//!
//! ```rust,ignore
//! // build.rs
//! fn main() {
//!     anchor_asm::build("src/asm");
//! }
//! ```
//!
//! ```rust,ignore
//! // lib.rs
//! #![feature(asm_experimental_arch)]
//! use anchor_lang_v2::prelude::*;
//!
//! declare_id!("...");
//!
//! anchor_asm::include_asm!();
//!
//! #[account]
//! pub struct MyState {
//!     pub value: u64,
//!     pub bump: u8,
//! }
//! ```
//!
//! Assembly files in `src/asm/` can reference generated constants:
//!
//! ```asm
//! entrypoint:
//!     ldxdw r3, [r1 + MyState__value]
//!     ldxb  r4, [r1 + MyState__bump]
//!     mov32 r5, MyState__SIZE
//! ```
//!
//! # What it does
//!
//! 1. **`build("src/asm")`** (called from `build.rs`):
//!    - Walks the assembly directory for `.s` files
//!    - Parses `lib.rs` for `#[account]` structs
//!    - Emits `.equ` constants for field offsets, struct sizes, and
//!      discriminators
//!    - Concatenates all `.s` files (expanding `.include` directives)
//!    - Writes `$OUT_DIR/combined.s`
//!
//! 2. **`include_asm!()`** (called from `lib.rs`):
//!    - Expands to `global_asm!(include_str!(...))` referencing the
//!      combined output

mod preamble;

use std::path::{Path, PathBuf};

/// Emit `global_asm!` linking the combined assembly output from `build()`.
///
/// Must be called at crate root scope. Requires
/// `#![feature(asm_experimental_arch)]` on the crate.
#[macro_export]
macro_rules! include_asm {
    () => {
        core::arch::global_asm!(include_str!(concat!(env!("OUT_DIR"), "/combined.s")));
    };
}

/// Build-time entry point. Call from `build.rs` with the path to the
/// assembly source directory (relative to the crate root).
///
/// Reads `src/lib.rs` for `#[account]` structs to generate offset
/// constants, then collects and concatenates all `.s` files from
/// `asm_dir` into `$OUT_DIR/combined.s`.
pub fn build(asm_dir: &str) {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"),
    );
    let out_dir = PathBuf::from(
        std::env::var("OUT_DIR").expect("OUT_DIR not set"),
    );
    let asm_path = manifest_dir.join(asm_dir);
    let lib_rs = manifest_dir.join("src").join("lib.rs");

    // Generate .equ preamble from #[account] structs.
    let preamble = if lib_rs.exists() {
        preamble::generate(&lib_rs)
    } else {
        String::new()
    };

    // Collect and concatenate assembly files.
    let combined = collect_asm(&asm_path);

    let output = format!(
        "# Auto-generated by anchor-asm. Do not edit.\n\
         #\n\
         # Struct field offsets and sizes from #[account] structs.\n\
         # Assembly files from {asm_dir}/.\n\
         \n\
         {preamble}\n\
         {combined}"
    );

    std::fs::write(out_dir.join("combined.s"), output).expect("write combined.s");

    // Rerun if any assembly file or lib.rs changes.
    println!("cargo:rerun-if-changed={asm_dir}");
    println!("cargo:rerun-if-changed=src/lib.rs");
}

/// Recursively collect all `.s` files from `dir`, concatenating their
/// contents. Files are sorted by path for deterministic output.
/// `.include` directives are expanded inline.
fn collect_asm(dir: &Path) -> String {
    let mut files: Vec<PathBuf> = Vec::new();
    walk_dir(dir, &mut files);
    files.sort();

    // Check for a root entry file (e.g. `entrypoint.s` or a file matching
    // the directory name). If present, process it first — it typically
    // contains `.include` directives that set the ordering.
    let root_file = find_root_file(dir, &files);

    if let Some(root) = root_file {
        // Process the root file, expanding .include directives.
        expand_includes(&root, dir)
    } else {
        // No root file — concatenate all files in sorted order.
        let mut out = String::new();
        for file in &files {
            let content = std::fs::read_to_string(file)
                .unwrap_or_else(|e| panic!("read {}: {e}", file.display()));
            out.push_str(&format!(
                "# --- {} ---\n",
                file.strip_prefix(dir).unwrap_or(file).display()
            ));
            out.push_str(&content);
            out.push('\n');
        }
        out
    }
}

/// Find a root assembly file that should be processed first. Checks for
/// `entrypoint.s` or a file matching the directory name.
fn find_root_file(dir: &Path, files: &[PathBuf]) -> Option<PathBuf> {
    let candidates = ["entrypoint.s", "main.s"];

    // Check for well-known names.
    for name in &candidates {
        let candidate = dir.join(name);
        if files.contains(&candidate) {
            return Some(candidate);
        }
    }

    // Check for dir-name.s (e.g. dropset/dropset.s).
    if let Some(dir_name) = dir.file_name().and_then(|n| n.to_str()) {
        let candidate = dir.join(format!("{dir_name}.s"));
        if files.contains(&candidate) {
            return Some(candidate);
        }
    }

    None
}

/// Recursively expand `.include` directives in an assembly file.
fn expand_includes(path: &Path, base_dir: &Path) -> String {
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));

    let mut out = String::new();
    let rel = path.strip_prefix(base_dir).unwrap_or(path);
    out.push_str(&format!("# --- {} ---\n", rel.display()));

    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix(".include") {
            let file = rest.trim().trim_matches('"');
            let include_path = path.parent().unwrap_or(base_dir).join(file);
            if include_path.exists() {
                out.push_str(&expand_includes(&include_path, base_dir));
            } else {
                // Try relative to base_dir.
                let from_base = base_dir.join(file);
                if from_base.exists() {
                    out.push_str(&expand_includes(&from_base, base_dir));
                } else {
                    // Keep the directive as-is — LLVM might resolve it.
                    out.push_str(line);
                    out.push('\n');
                }
            }
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

/// Walk a directory recursively, collecting `.s` file paths.
fn walk_dir(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk_dir(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("s") {
            out.push(path);
        }
    }
}
