name: "Setup Solana"
description: "Setup Solana"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      name: Cache Solana Tool Suite
      id: cache-solana
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-${{ runner.os }}-v0000-${{ env.SOLANA_VERSION }}
    - uses: nick-fields/retry@v2
      if: steps.cache-solana.outputs.cache-hit != 'true'
      with:
        retry_wait_seconds: 300
        timeout_minutes: 2
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          baseUrl="https://release.anza.xyz/v${{ env.SOLANA_VERSION }}"
          if [ "${{ runner.os }}" = "Windows" ]; then
            installer="${{ runner.temp }}/agave-install-init.exe"
            curl "${baseUrl}/agave-install-init-x86_64-pc-windows-msvc.exe" \
              --output "${installer}" \
              --create-dirs

            "${installer}" v${{ env.SOLANA_VERSION }}
          else
            sh -c "$(curl -sSfL "${baseUrl}/install")"
          fi
    - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash
    - run: solana-keygen new --no-bip39-passphrase
      shell: bash
    - run: solana config set --url localhost
      shell: bash
