[package]
name = "anchor-attribute-error"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Anchor attribute macro for creating error types"
edition.workspace = true

[lib]
proc-macro = true

[features]
anchor-debug = ["anchor-syn/anchor-debug"]
idl-build = ["anchor-syn/idl-build"]

[dependencies]
anchor-syn = { path = "../../syn", version = "0.31.1" }
quote.workspace = true
syn = { workspace = true, features = ["full"] }
