use pinocchio::{account::AccountView, address::Address};

pub struct Context<'a, T: Bumps> {
    /// Program id as a reference to avoid the 32-byte copy into every
    /// `Context` instance. The referenced `Address` lives for the whole
    /// instruction since it comes from the entrypoint's input buffer.
    pub program_id: &'a Address,
    pub accounts: T,
    pub remaining_accounts: &'a [AccountView],
    /// Bump seeds found during constraint validation. This is provided as a
    /// convenience so that handlers don't have to recalculate bump seeds or
    /// pass them in as arguments.
    /// Type is the bumps struct generated by `#[derive(Accounts)]`.
    pub bumps: T::Bumps,
}

impl<'a, T: Bumps> Context<'a, T> {
    #[inline(always)]
    pub fn new(
        program_id: &'a Address,
        accounts: T,
        remaining_accounts: &'a [AccountView],
        bumps: T::Bumps,
    ) -> Self {
        Self { program_id, accounts, remaining_accounts, bumps }
    }
}

/// Trait linking an accounts struct to its generated bumps struct.
pub trait Bumps {
    type Bumps;
}
