use anchor_lang_v2::prelude::*;

declare_id!("4vJ9JU1bJJE96FWSJKvHsmmFADCg4gpZQff4P3bkLKi");

#[program]
pub mod callee {
    use super::*;

    pub fn initialize(ctx: &mut Context<Initialize>) -> Result<()> {
        ctx.accounts.data.value = 0;
        ctx.accounts.data.authority = *ctx.accounts.authority.address();
        Ok(())
    }

    pub fn set_data(ctx: &mut Context<SetData>, value: u64) -> Result<()> {
        ctx.accounts.data.value = value;
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {
    #[account(mut)]
    pub payer: Signer,
    #[account(
        init,
        payer = payer,
        space = 8 + core::mem::size_of::<DataAccount>(),
        seeds = [b"data"],
        bump,
    )]
    pub data: Account<DataAccount>,
    pub authority: Signer,
    pub system_program: Program<System>,
}

#[derive(Accounts)]
#[instruction(value: u64)]
pub struct SetData {
    #[account(mut, seeds = [b"data"], bump)]
    pub data: Account<DataAccount>,
    #[account(address = data.authority)]
    pub authority: Signer,
}

#[account]
pub struct DataAccount {
    pub value: u64,
    pub authority: Address,
}

/// Manual CPI module — will be auto-generated by derive macro in the future.
#[cfg(feature = "cpi")]
pub mod cpi {
    extern crate alloc;
    use {
        alloc::{vec, vec::Vec},
        anchor_lang_v2::{
            cpi::InstructionAccount, CpiContext, CpiHandle, InstructionData, ToCpiAccounts,
        },
        solana_program_error::ProgramError,
    };

    pub mod accounts {
        use super::*;

        pub struct SetData<'a> {
            /// Writable data account — caller passes `cpi_handle_mut`.
            pub data: CpiHandle<'a>,
            /// Read-only authority signer — caller passes `cpi_handle`.
            pub authority: CpiHandle<'a>,
        }

        impl<'a> ToCpiAccounts<'a> for SetData<'a> {
            fn to_instruction_accounts(&self) -> Vec<InstructionAccount<'a>> {
                vec![
                    InstructionAccount::writable(self.data.address()),
                    InstructionAccount::readonly_signer(self.authority.address()),
                ]
            }

            fn to_cpi_handles(&self) -> Vec<CpiHandle<'a>> {
                vec![self.data, self.authority]
            }
        }
    }

    pub fn set_data<'a>(
        ctx: CpiContext<'a, accounts::SetData<'a>>,
        value: u64,
    ) -> Result<(), ProgramError> {
        let ix_data = crate::instruction::SetData { value }.data();
        ctx.invoke(&ix_data)
    }
}
