name: Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    name: Reusable
    uses: ./.github/workflows/reusable-tests.yaml
    with:
      cache: true
      solana_cli_version: 2.1.0
      node_version: 20.18.0
      cargo_profile: debug
      anchor_binary_name: anchor-binary
